monitor.bluez.properties = {
    # Evita que o sistema mude para som de baixa qualidade sozinho
    bluetooth.autoswitch-to-headset-profile = false
    
    # Permite que o fone conecte todas as funções (corrige a falha de conexão)
    bluez5.roles = [ a2dp_sink a2dp_source headset_head_unit headset_audio_gateway ]
    
    # Força o sistema a preferir codecs de alta fidelidade como padrão de fábrica
    bluez5.codecs = [ ldac aac aptx aptx_hd sbc_xq sbc ]
}

wireplumber.settings = {
    # Mantém a troca automática de saída ao conectar
    device.routes.default-sink-switch = true
}
