# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1E0528)
$foreground = rgb(FFEEFF)
$color0 = rgb(1E0528)
$color1 = rgb(00D9E9)
$color2 = rgb(05CB0D)
$color3 = rgb(955AE7)
$color4 = rgb(550068)
$color5 = rgb(8991BB)
$color6 = rgb(B900B1)
$color7 = rgb(FFEEFF)
$color8 = rgb(320F55)
$color9 = rgb(00D9E9)
$color10 = rgb(05CB0D)
$color11 = rgb(955AE7)
$color12 = rgb(550068)
$color13 = rgb(8991BB)
$color14 = rgb(B900B1)
$color15 = rgb(F8C0FF)
