# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FFEEFF
background         #1E0528
cursor             #FFEEFF

active_tab_foreground     #1E0528
active_tab_background     #FFEEFF
inactive_tab_foreground   #FFEEFF
inactive_tab_background   #1E0528

active_border_color   #FFEEFF
inactive_border_color #1E0528
bell_border_color     #00D9E9

color0      #1E0528
color1		#00D9E9
color2		#05CB0D
color3		#955AE7
color4		#550068
color5		#8991BB
color6		#B900B1
color7		#FFEEFF
color8		#320F55
color9		#00D9E9
color10		#05CB0D
color11		#955AE7
color12		#550068
color13		#8991BB
color14		#B900B1
color15		#F8C0FF
