# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

#BACKUP
#$background = rgb(1E0528)
#$foreground = rgb(FFEEFF)
#$color0 = rgb(1E0528)
#$color1 = rgb(00D9E9)
#$color2 = rgb(05CB0D)
#$color3 = rgb(955AE7)
#$color4 = rgb(550068)
#$color5 = rgb(8991BB)
#$color6 = rgb(B900B1)
#$color7 = rgb(FFEEFF)
#$color8 = rgb(320F55)
#$color9 = rgb(00D9E9)
#$color10 = rgb(05CB0D)
#$color11 = rgb(955AE7)
#$color12 = rgb(550068)
#$color13 = rgb(8991BB)
#$color14 = rgb(B900B1)
#$color15 = rgb(F8C0FF)

# Fundo Profundo e Texto Claro Estelar
$background = rgb(0B0914)
$foreground = rgb(E2D9F3)

# Tons Escuros / Base (Preto Espacial e Roxos Fechados)
$color0 = rgb(0B0914)
$color8 = rgb(161224)

# Roxo Médio / Sombras de Fundo
$color4 = rgb(322A4D)
$color12 = rgb(5B3BA8)

# Roxo Principal / Magenta Místico (Bordas Ativas, etc.)
$color5 = rgb(8A2BE2)
$color13 = rgb(8261E6)

# O Novo Rosa Cósmico (Substituindo o antigo Ciano)
$color1 = rgb(D34E9B)
$color9 = rgb(E86BB5)

# O Seu Dourado Fosco Elegante (Substituindo o antigo Verde)
$color2 = rgb(D4AF37)
$color10 = rgb(E5C158)

# Tons de Transição / Nebulosa
$color3 = rgb(955AE7)
$color11 = rgb(A052FF)

# Rosa Choque / Detalhes de Alerta
$color6 = rgb(B900B1)
$color14 = rgb(F8C0FF)

# Branco Estelar / Brilho Máximo
$color7 = rgb(DEE2E6)
$color15 = rgb(FFFFFF)
